#!/bin/python3

from os import sys
from os import sys
import calcul

def parser():
    if (len(sys.argv) < 3 or len(sys.argv) > 5):
        quit (84)
    try:
        mu = int(sys.argv[1])
        sigma = int(sys.argv[2])
    except:
        quit (84)
    if (mu < 0 or mu > 200 or sigma <= 0):
        quit (84)
    mode = len(sys.argv) - 2
    return mode, mu, sigma

def redirect(mode, mu, sigma):
    if (mode == 1):
        calcul.mode_1(mu, sigma)
    elif (mode == 2):
        result = calcul.mode_2(mu, sigma, sys.argv[3])
        print("%.1f" % result, "% " ,"of people have an IQ inferior to ", sys.argv[3], sep='')
    else:
        calcul.mode_3(mu, sigma, sys.argv[3], sys.argv[4])
    return

mode, mu, sigma = parser()
redirect(mode, mu, sigma)