#!/bin/python3

from os import sys
from os import sys
from calcul import *

def parser():
    if (len(sys.argv) < 3 or len(sys.argv) > 5):
        quit (84)
    try:
        mu = int(sys.argv[1])
        sigma = int(sys.argv[2])
    except:
        quit (84)
    mode = len(sys.argv) - 2
    return mode, mu, sigma

mod, mu, sigma = parser()
print(mod, mu, sigma)